### PR TITLE
Fix issue on verticalMultilineAtDefinitionSite

### PR DESCRIPTION
**Pull request by pjrt**
Fixes an issue where verticalMultilineAtDefinitionSite affected classes,
instead of just `def` sites.

### CODE REVIEW

**Comment by pjrt** [comment]
Yes, I was thinking that actually. Will do.

**Comment by olafurpg** [comment]
I have been impressed with your contributions @pjrt. I am curious to know, would you be interested in becoming a scalafmt maintainer?

You would have merge rights and be listed in the readme/docs as such. With all the recent contributions and activity around the project, I could use some extra help.

If you don't have time or motivation, I totally understand. Even if you approve, please don't feel pressured to take on a responsibility unless you're personally motivated to work on said task. If you later change your mind then that's totally fine, too.

**Comment by pjrt** [comment]
Sure! This all started as just trying to make a specific style we are using work with Scalafmt. But I've actually become intrigued by the project and your paper (which I haven't finished yet).

So yeah, I would love to be a contributor. I'll try to put aside some hours to fix the outstanding issues.

**Comment by olafurpg** [comment]
Awesome! I'm happy to hear that 😸 

I'll update the docs/readme then.

**Pull request merged**
