### PR TITLE
Polish infix indentation around assignment.

### LINKED ISSUE #701: Weird indent caused by infix application
## Unexpected formatting output

```diff
+lazy val paradiseRoot = Project(
+    id = "paradiseRoot",
+    base = file(".")
+  ) settings (
+    sharedSettings,
+    packagedArtifacts := Map.empty,
+    aggregate in publish := false,
+    publish := {
+    val publishPlugin = (publish in plugin in Compile).value
+  },
-    }, 
```

### PR DESCRIPTION
**Pull request by olafurpg**
Fixes #701

### CODE REVIEW

**Comment by olafurpg** [comment]
This is a rather big change to the indentation rules for infix operators, example

```diff
         t = 1.2 * sq * (1.0 + y * y) * exp(
-            nfact - breeze.numerics.lgamma(bnl + 1.0) -
-              breeze.numerics.lgamma(n - bnl + 1.0) +
-              bnl * plog + (n - bnl) * pclog
-          )
+          nfact - breeze.numerics.lgamma(bnl + 1.0) -
+            breeze.numerics.lgamma(n - bnl + 1.0) +
+            bnl * plog + (n - bnl) * pclog
+        )
       } while (rand.uniform.get > t)

...
           run = run bindA
-              (aliasDef.name, { () =>
+            (aliasDef.name, { () =>
               aliasDef.aliasedType(TypingContext.empty).getOrAny
             })
```

Full diff from scala-repos https://github.com/olafurpg/scala-repos/commit/cedb228e2389b609036b997459a0148c6cd39d6c

[diff.zip](https://github.com/olafurpg/scalafmt/files/787569/diff.zip)


What do you think @pjrt @ysusuk ?

**Comment by ysusuk** [comment]
a good one will be to enable AvoidInfix! and there won't be infix ops anymore ^_^

**Comment by ysusuk** [comment]
Looks awesome 👍  
Not sure about this one:

```diff
   private lazy val propertyName =
     ("""[a-zA-Z_][a-zA-Z_0-9]*""".r | """`([^`\\]|\\.)+`""".r ^^ canonicalizePropertyName | """"([^"\\]|\\.)+"""".r ^^ canonicalizeStr //"
-    )
+  )
```

**Comment by olafurpg** [comment]
Ghargh, good catch. I'll take a look at that one. Should also try and fix

```scala
a ::
  b ::
    c ::
      d ...
```

**Comment by olafurpg** [comment]
@ysusuk Aah, I didn't notice the comment there, that's why it looks so weird. Yes, I agree that example is unfortunate, but I don't see a way to get around this corner case. The parentheses are redundant, so the ugly formatting might help push the author remove them.

**Pull request merged**
