### PR TITLE
Add adopter: Teralytics

### PR DESCRIPTION
**Pull request by stefanobaghino**

### CODE REVIEW

**Comment by olafurpg** [comment]
Could you rebase?

**Comment by olafurpg** [comment]
Thanks! I should probably exclude this file for coverage.

**Comment by stefanobaghino** [comment]
Or, you could add tests for adopters, like checking if the URL is correct. #EXTREMETESTING

**Comment by olafurpg** [comment]
Scalatex already validates all links ;)

**Comment by stefanobaghino** [comment]
Neat!

**Pull request merged**
