### PR TITLE
Fixes #399 - Automate IntelliJ Plugin Update

### LINKED ISSUE #399: Automate IntelliJ plugin update
The publish step for the plugin is too manual so I don't bother for tiny releases, causing #398. The Jetbrains guys showed me at ScalaDays how they build and upload the Scala plugin automatically. It would be great to do something similar for scalafmt.

### PR DESCRIPTION
**Pull request by rbellamy**
Fixes #399.

* Create `intellij` sub-project and move its files into standard directory structure
* Add `sbt-idea` plugin and wire it up to to the `intellij` sub-project:
  - `intellij/updateIdea` puts files in `intellij/idea`
  - `intellij/compile` compiles the plugin
  - `intellij/clean` cleans `target` and `idea`

### CODE REVIEW

**Comment by olafurpg** [comment]
Wow! Thank you for this contribution. I am very excited to get this merged. Did you manage to build/run the intellij plugin locally?

I cloned your PR and managed to compile the plugin via sbt, which is very nice 👍. However, I still haven't figured out how to build the zip file that I usually upload to plugins.jetbrains.com. I tried following [these instructions](https://github.com/rikvdkleij/intellij-haskell#how-to-build-project) but with no luck.

**Comment by rbellamy** [comment]
Reading the [`intellij-haskell` How to Prepare Plugin for Deployment](https://github.com/rikvdkleij/intellij-haskell#how-to-prepare-plugin-for-deployment) instructions it's clear they're geared toward a project that is solely an Intellij Plugin project, and that the archive (whether JAR or ZIP) is created with IntelliJ itself.

Specifically, the point `Prepare Plugin Module 'intellij-haskell' for deployment` which I believe points to [this help section in IntelliJ](https://www.jetbrains.com/help/idea/2016.3/preparing-plugins-for-publishing.html).

I just went through the process of installing the plugin created with the `intellij/package` task, and received the following exception from IntelliJ on reload, so it looks like the plugin JAR is missing some dependencies:

```
Plugin 'org.scalafmt.ScalaFmt' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NoClassDefFoundError: scala/collection/Seq
    at org.scalafmt.intellij.OnFileSaveComponent.getComponentName(OnFileSaveComponent.scala:11)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:427)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.access$300(ComponentManagerImpl.java:58)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:492)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:125)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:444)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:451)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:109)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:403)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:389)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:69)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: scala.collection.Seq PluginClassLoader[org.scalafmt.ScalaFmt, 0.5.1]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:64)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 36 more
```

**Comment by rbellamy** [comment]
Looks like the folks over at JetBrains decorate their IntelliJ Scala plugin with [one-off plugins to help them with packaging](https://github.com/JetBrains/intellij-scala/blob/idea163.x/project/Packaging.scala).

**Comment by rbellamy** [comment]
I'm a bit confused by what the `sbt-idea-plugin` is doing with the `unmanagedJars` and the `libraryDependencies` - the `publishPlugin` task is doing something different than the process IntelliJ goes through to package up a plugin.

For instance, with the recipe you were trying to follow, the expectation is that the `unmanagedJars` should be marked as `% provided`, but the plugin doesn't do that. It also appears from the exception I saw on reload of IntelliJ that the plugin JAR should actually be a fat JAR that includes the Scala runtime libraries... but that doesn't make sense as that would mean that every Scala-related plugin would be shipping those libraries.

I'm stumped.

**Comment by rbellamy** [comment]
Oh. And one more thing (in case it wasn't clear from my other comments) - the `sbt-idea-plugin` doesn't create a ZIP artifact - it creates and uploads a JAR.

**Comment by olafurpg** [comment]
It seems sbt-idea-plugin doesn't correctly create a zip file for deployment, at least `ideaPluginFile` doesn't seem to do the right thing for me. `ideaPublishPlugin` yields a 404 error. Nevertheless, I copied the project structure from intellij-haskell and was able to get "Prepare module for deployment" working. This PR is a huge win since the `intellij` project is now part of the main sbt build making it a whole lot easier to test/run! Previously, you needed to open a separate intellij project and copy the assembly output into `intellij/lib` (very fragile process).

I verified manually that I can still publish the sbt plugin with my previous publish workflow, so I'm happy to merge this now. Hopefully I can automate the publish step later with `ideaPluginPublish`. LGTM 👍 Thanks a lot, I'm really excited to get this in :) 

cc/ @joan38

**Pull request merged**
