### PR TITLE
Add style config to keep new lines on chained method calls

### PR DESCRIPTION
**Pull request by melrief**

### CODE REVIEW

**Comment by melrief** [comment]
I forgot to remove the `ONLY` on the tests in the first commit and I did 54e5943 to fix it, I suggest to squash the commits if you merge.

**Comment by melrief** [comment]
Rebased on master

**Comment by olafurpg** [comment]
LGTM. Only comments

- add an option in Cli.scala so that users can configure this options.
- squash everything into one commit.

**Comment by melrief** [comment]
The issue that CI is showing is

```scala
sbt.ResolveException: unresolved dependency: pl.project13.scala#sbt-jmh;0.2.6: not found
```

which I don't think this PR added. @olafurpg do you have any idea of what I should do? I already rerun the tests...

**Comment by olafurpg** [comment]
@melrief That seems to be drone related since Travis is green. However, could you rebase on master?

I forgot that I worked last Friday on auto publishing gh-pages docs from Travis and disabled the mega test suite to experiment faster. I didn't expect to receive so many nice PRs this weekend :) I've re-enabled the mega test suite now so I would like to run that before merging.

**Comment by olafurpg** [comment]
LGTM, thanks! 😄

**Comment by olafurpg** [comment]
@melrief FYI, I renamed the flag to `optIn.breakChainOnFirstMethodDot` following feedback from #444. I grouped it in `optIn` since you opt-into breaking the chain similarly as you opt-into config style. I hope this makes sense.

**Comment by melrief** [comment]
It does :)

**Pull request merged**
