### PR TITLE
Move Settings at project level

### PR DESCRIPTION
**Pull request by joan38**
I just moved the app setting at project level.
So if you want to set it globally you can set it for all your current projects in `Preferences...` and for all future projects in `File` > `Other settings` > `Default Settings...`

### CODE REVIEW

**Comment by olafurpg** [comment]
I tried this out. The settings menu looks great. However, it appears that format runs now randomly during editing, before I press save. Here is a gif where I press enter non-stop

save

I did not experience this with the previous PR. Any idea what might be the cause?

**Comment by joan38** [comment]
I can't reproduce the issue.

On a separate point. I'm trying to resolve an issue when the formatter can't format it will display a ballon with this message:
```
Parse error: <input>:5: error: } expected but end of file found
```
Which is displayed like this:
screen shot 2016-10-23 at 14 01 53

Is order to resolve this issue, I need the lib `scala-xml`, do you know how I can add this lib? Do we use SBT for this project? I don't understand how the project `scalafmtIntellij` is working.

Cheers

**Comment by joan38** [comment]
This new commit fixes the HTML (see below pic), I had to import `scala-xml.jar` manually in Idea to make it work so not sure how to do with SBT.
screen shot 2016-10-23 at 14 12 28

**Comment by olafurpg** [comment]
> I don't understand how the project scalafmtIntellij is working.

I'm sorry about that, the scalafmtIntellij project is not used so it shouldn't even be part of the build. I don't know why it even got merged. I've been planning to move to https://github.com/dancingrobot84/sbt-idea-plugin for a while now but never got it working. For now, I just `sbt cli/assembly` and manually copy paste the fat jar to `intellij/lib` 

>  I had to import scala-xml.jar manually in Idea to make it work so not sure how to do with SBT.

Would it be possible to escape the angle brackets? That message should not be rendered as html. In either case, as long as the dependency is defined in `intellij.iml` then my idea project will pick it up.

> I can't reproduce the issue.

Let me give it another try.

**Comment by joan38** [comment]
> Would it be possible to escape the angle brackets? That message should not be rendered as html. In either case, as long as the dependency is defined in intellij.iml then my idea project will pick it up.
Is it ok then now with my last commit?

**Comment by olafurpg** [comment]
The project doesn't build because of the missing scala-xml library.

**Comment by joan38** [comment]
Which line number is the best to add this dep in `build.sbt`?

**Comment by olafurpg** [comment]
I'm investigating if we can use some package in com.intellij to escape xml strings, adding scala-xml seems overkill

**Comment by olafurpg** [comment]
Okay, I couldn't quickly find any Xml escape method in com.intellij.xml. We can use scala-xml, I think the dependency needs to be listed in `intellij.iml`. It should automatically add to `intellij.iml` when you add the dependency in the project settings.

**Comment by olafurpg** [comment]
Something like this


```xml
    <orderEntry type="library" name="org.scala-lang.modules:scala-xml_2.11:1.0.6" level="project" />
```

**Comment by joan38** [comment]
But I don't see where the scalafmt lib is described there?

**Comment by olafurpg** [comment]
Scalafmt is not described there, it's just an unmanaged dependency. I copy paste the fat jar in to `lib`. I admit this is terribly undocumented.

 #399 is the plan to move the intellij project into the main SBT build, I just haven't found the time get it done.

**Comment by joan38** [comment]
Ok I can do what you mentioned, and that can be then moved at SBT level later.

**Comment by joan38** [comment]
Done. Have you resolved your issue with random reformatting?

**Comment by olafurpg** [comment]
That sounds like a good plan. Could you also remove `scalafmtIntellij` from build.sbt, to avoid further confusion?

**Comment by olafurpg** [comment]
I am unable to reproduce the "saves randomly, not only on save" error once I build the plugin zip and install manually. So this PR is good to go as soon as scalafmtIntellij is out from build.sbt

**Comment by joan38** [comment]
Sure, I will also do https://github.com/olafurpg/scalafmt/pull/548#discussion_r84596257

**Comment by olafurpg** [comment]
Awesome! Thanks a lot :)

**Comment by joan38** [comment]
No worries, I will have a look to https://github.com/olafurpg/scalafmt/issues/518 later next week.

**Comment by joan38** [comment]
@olafurpg Did we updated the plugin zip file in the release with this change?

**Comment by olafurpg** [comment]
@joan38 No, I had forgotten. I've updated the zip now: https://github.com/olafurpg/scalafmt/releases/download/v0.4.7/intellij-4.7-autosave.zip

I hope to release 0.4.8 soon, once I find the time to write up the changelog.

**Comment by olafurpg** [comment]
Scalafmt is not described there, it's just an unmanaged dependency. I copy
paste the fat jar in to `lib`. I admit this is terribly undocumented, sorry
about that.  #399 is the plan to clean up the intellij project to make the
project a lot easier to work with, I just haven't found the time get it
done.

**Pull request merged**
